name: CI

on:
    push:
        branches:
        - master
        - '*CI*'
    pull_request:
        branches:
        - '*'

jobs:
  frontend_tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - uses: actions/checkout@v1
      with:
        submodules: True

    - name: Install deps
      run: npm ci

    - name: Run frontend tests
      run: npx grunt test_no_watch

  eslint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - uses: actions/checkout@v1
      with:
        submodules: True

    - name: Install deps
      run: npm ci

    - name: Run eslint
      run: npx grunt eslint
